### ISSUE TITLE
Did this binding works for you?

### ISSUE THREAD

**Issue by melanke** [ianlevesque/calligraphy-xamarin#1]
I am trying to use this binding but the app crashes just with "using Calligraphy;"

I've downloaded the solution, build it, and created a reference to the DLL in /bin/Release/

Could you help me? Could you send me the DLL? Thank you very much.

**Comment by ianlevesque** [comment]
Yes it works, it is being used in an app right now.  Here's a build: http://cl.ly/0b3o3G3p3235/download/Calligraphy.dll

It's hard to say what else would be going wrong from your description.  If you want one on one help, I'm available on hackhands https://hackhands.com/ianlevesque

**Comment by melanke** [comment]
Thank you
